name: Build and Install

on:
  push:
    branches: [ maestro ]
  pull_request:
    branches: [ maestro ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        goos: ['linux', 'darwin', 'windows']
        include:
          - os: ubuntu-latest
            goos: linux
          - os: macos-latest
            goos: darwin
          - os: windows-latest
            goos: windows
            
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18

    - name: Install Dependencies and Build
      run: |
        if [[ "${{ runner.os }}" == "Linux" ]]; then
          bash ./install-libheif.sh
        elif [[ "${{ runner.os }}" == "macOS" ]]; then
          bash ./install-libheif-macos.sh
        elif [[ "${{ runner.os }}" == "Windows" ]]; then
          cmd.exe /c .\install-libheif-windows.bat
        fi
        mkdir -p bin
        GOOS=${{ matrix.goos }} go build -o bin/heif-converter-${{ matrix.goos }}

    - name: Archive Production Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: heif-converter-${{ matrix.os }}
        path: |
          ./bin/*
