name: Build and Install

on:
  push:
    branches: [ maestro ]
  pull_request:
    branches: [ maestro ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            goos: linux
            archs: ['amd64', 'arm64']
          - os: macos-latest
            goos: darwin
            archs: ['amd64']  #, 'arm64' -- Uncomment this to enable cross-compiling for macOS on ARM64
          - os: windows-latest
            goos: windows
            archs: ['amd64']
            
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18

    - name: Install Dependencies and Build
      run: |
        if [[ "${{ runner.os }}" == "Linux" ]]; then
          bash ./install-libheif.sh
        elif [[ "${{ runner.os }}" == "macOS" ]]; then
          bash ./install-libheif-macos.sh
        elif [[ "${{ runner.os }}" == "Windows" ]]; then
          cmd.exe /c .\install-libheif-windows.bat
        fi
        mkdir -p bin
        for arch in ${{ join(matrix.archs, ' ') }}; do
          GOOS=${{ matrix.goos }} GOARCH=$arch go build -o bin/heif-converter-${{ matrix.goos }}-$arch
        done

    - name: Archive Production Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: heif-converter-${{ matrix.os }}
        path: |
          ./bin/*
