jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: false
            
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
    
    - name: Set up Vcpkg
      if: runner.os == 'Windows'
      uses: lukka/run-vcpkg@v8
      with:
        vcpkgArguments: 'libheif'
        vcpkgDirectory: '${{ runner.workspace }}/vcpkg/'
        vcpkgTriplet: 'x64-windows'

    - name: Install Dependencies and Build on Linux
      if: runner.os == 'Linux'
      run: |
        bash ./install-libheif.sh
        go test
        GOOS=linux go build -o bin/heif-converter-linux

    - name: Install Dependencies and Build on macOS
      if: runner.os == 'macOS'
      run: |
        bash ./install-libheif-macos.sh
        go test
        GOOS=darwin go build -o bin/heif-converter-macos

    - name: Build on Windows
      env:
        PKG_CONFIG_PATH: C:/src/vcpkg
      if: runner.os == 'Windows'
      run: |
        go test
        go build -o bin/heif-converter-windows.exe

    - name: Archive Production Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: heif-converter-${{ runner.os }}
        path: |
          ./bin/*
